### ISSUE TITLE
Nice Idea

### ISSUE THREAD

**Issue by idkjs** [arackaf/mongo-graphql-starter#1]
I just tried to run your simple example. Looks like its only generating the books files.
This the error im getting:

```js
$ babel-node create.js
(node:14463) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT:no such file or directory, open '/Users/shingdev/code/graphql-metadata copy/src/createGraphqlSchema/resolverTemplate.js'
(node:14463) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
- test dir tree
```
$ tree
├── create.js
├── index.js
├── node_modules
├── package-lock.json
├── package.json
├── projectSetupA.js
└── test
     └── testProject1
        └── graphQL
            └── Book
                ├── Book.js
               └── schema.js


3 directories, 2 files
```

FYI

**Comment by arackaf** [comment]
What's in create.js?  I'm not getting this error, but the latest @std/esm is indeed throwing a separate error, so there's definitely something else wrong...

**Comment by arackaf** [comment]
Here's a fully working repo that generates the schema and resolvers

https://github.com/arackaf/test-mongo-graphql-starter

after npm installing, either run `node index` to see it work with the ESM loader, or `node runItNode` for the pure Node solution.  I'll prolly polish this repo up and wind up adding it to the docs

**Comment by idkjs** [comment]
Thank you, sir. I will check it out.

**Comment by idkjs** [comment]
Both run commands produce this error.

I downgraded npm to 5.3 per an npm issue on the matter. I guess I'll edit your code to check for the directory and use mkdir or mkdirp but figured you would want to be aware. 

What node and npm version are you using that you are not getting this error? Im using Node 8.2.1 and Npm 5.3. 

```bsh
shingdev at cosmos in ~/code/test-mongo-graphql-starter-master
$ node index.js
(node:1237) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, mkdir '/Users/shingdev/code/test-mongo-graphql-starter-master/testProject1/graphQL'
(node:1237) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

shingdev at cosmos in ~/code/test-mongo-graphql-starter-master
$ node runItNode
(node:1430) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, mkdir '/Users/shingdev/code/test-mongo-graphql-starter-master/testProject1/graphQL'
(node:1430) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by arackaf** [comment]
Ah well the target directory has to exist - just create a `testProject1` folder, and it should work.  I suppose I could do a better job of dynamically creating the needed folders as this thing runs :)

**Comment by idkjs** [comment]
That worked. Did that the first time around on the original from readme. Just figured you had something set up and wanted to let it do what it does. Nice mongo codegen

**Comment by arackaf** [comment]
Thanks!  Still a little rough around some edges, as you no doubt realize by now :)

**Comment by arackaf** [comment]
Ugh solution was so simple, too :(

https://github.com/substack/node-mkdirp 

Will try to get a patch version out tonight

**Comment by idkjs** [comment]
Why we talk, boss.

**Comment by idkjs** [comment]
Thinking about the workflow here. Using this as you have it set up feels messy. Like, i would have to generate it then copy the folder to another project.  If I'm using this in a project, i'm thinking this is a dev dependency, and the generated project would be in the root directory. This would be a utility script that I can run every time I update something in my schema. 

What I did create a root folder /graphQL then
```js
createGraphqlSchema(projectSetup, path.resolve("./"));
```

So you testProject is really the database directory in a graphql server/client project.

Seems like the thing i have to work through is deleting and recreating the Author/Book/Subject directory. I've set up nodemon to watch projectSetupA.js which it does and reruns on changes but its not recreating the directories. Im thinking using https://github.com/isaacs/rimraf could do this, just need to figure it out. So this is where I'm at: https://github.com/idkjs/test-mgl-starter

**Comment by idkjs** [comment]
Something else I came up with, https://github.com/idkjs/hn-mongo-graphql-starter. 

- the script doesnt handle circular dependencies. Trying to figure that out here. I made each type in graphQL/projectSetupA.js a function but that threw this error that I'm not sure how to deal with.

```bsh
(node:6085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '_id' of undefined
(node:6085) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by idkjs** [comment]
worth checking out https://medium.com/@dotansimha/graphql-code-generator-a34e3785e6fb

**Comment by arackaf** [comment]
Few things:

New version is out which uses mkdirp, so folders are created as needed.

Circular deps:

Coming soon.  Forget functions - if you do

```javascript
import { dataTypes } from "mongo-graphql-starter";
const { MongoIdType, StringType, IntType, FloatType, DateType, arrayOf, objectOf, formattedDate, typeLiteral } = dataTypes;

const Author = {
  table: "authors",
  fields: {
    name: StringType,
    birthday: DateType
  }
};

const Book = {
  table: "books",
  fields: {
    _id: MongoIdType,
    title: StringType,
    pages: IntType,
    weight: FloatType,
    authors: arrayOf(Author),
    primaryAuthor: objectOf(Author),
    strArrs: typeLiteral("[[String]]"),
    createdOn: DateType,
    createdOnYearOnly: formattedDate({ format: "%Y" })
  }
};

Author.fields.books = arrayOf(Book);
```

then I'll just generate this 

```javascript
import Book from "../Book/Book";

export default {
  table: "authors",
  fields: {
    _id: "MongoId",
    name: "String",
    birthday: {
      __isDate: true,
      format: "%m/%d/%Y"
    },
    books: {
      __isArray: true,
      get type(){ return Book; }
    }
  }  
};
```

Note the getter :D 

Which mostly works

```javascript
test("test circular deps", async () => {
  let book = await runMutation({ schema, db, mutation: `createBook(title: "Book 2", pages: 100){_id, title, pages}`, result: "createBook" });
  let author = await runMutation({
    schema,
    db,
    mutation: `createAuthor(name: "Adam", books: [{ _id: "${book._id}", title: "${book.title}" }]){_id, name}`,
    result: "createAuthor"
  });

  await runMutation({
    schema,
    db,
    mutation: `updateBook(_id: "${book._id}", authors: [{ _id: "${author._id}", name: "${author.name}" }]){_id}`,
    result: "updateBook"
  });

  await queryAndMatchArray({
    schema,
    db,
    query: `{getBook(_id: "${book._id}"){_id, title, pages, authors { name }}}`,
    coll: "getBook",
    results: { _id: book._id, title: "Book 2", pages: 100, authors: [{ name: "Adam" }] }
  });
});

That test passes, but only because I didn't request _id from the author.  That doesn't work, but will dovetail nicely with some mutation updates I was already working on, so this'll prolly go out when that's done.

**Comment by arackaf** [comment]
Re your comments about the workflow, I'm not sure I understand.  My intention with this was that people would just generate their schema and resolvers right in their project.  Generate the files, and then use them, or add to them as needed (recall that the files are not overwritten by default, only the metadata files, so you could add in new fields to a type, re-gen, update the schema, and it should work.

Sucks to also have to manually also update the schema, but I want to avoid having the generated code be some sort of black box that the user can't touch / has to work around, so that's the tradeoff I'm working against.
