### ISSUE TITLE
How to deploy serverless Azure or AWS Lamba?

### ISSUE THREAD

**Issue by PhilAndrew** [arackaf/mongo-graphql-starter#11]
Hello, please tell me how to deploy this serverless on AWS Lambda

**Comment by arackaf** [comment]
No idea, sorry.  And I'm not really sure this would be a good fit for AWS Lambda. This project **generates** javascript for your project. I'm not sure why you'd want a code generation being run on Lambda. But regardless, I've never used Lambda so I'm not sure how to set anything up there.

**Comment by PhilAndrew** [comment]
I mean the code which was generated and which I can normally run, I want to run that on AWS Lambda for scalability.

**Comment by arackaf** [comment]
Still, no idea. I've never used Lambda. The code this utility generates is regular Node-based JavaScript, so ... however you normally run code on Lambda, should be no different for the code generated here.
