### ISSUE TITLE
Unescaped Input filter's RegExp

### ISSUE THREAD

**Issue by sergio91pt** [arackaf/mongo-graphql-starter#16]
In queryUtilities, method fillMongoFiltersObject, queryOperation's `contains`, `startsWith` and `endsWith` should have their input escaped.

**Comment by arackaf** [comment]
Can you be more specific?  What filter value are you sending over that's being treated incorrectly?

**Comment by sergio91pt** [comment]
Sure, I'm talking about these lines [#110](https://github.com/arackaf/mongo-graphql-starter/blob/74e1ea86703692f465a1d32abd5781b92581be7e/src/queryUtilities.js#L110), [#112](https://github.com/arackaf/mongo-graphql-starter/blob/74e1ea86703692f465a1d32abd5781b92581be7e/src/queryUtilities.js#L112), [#114](https://github.com/arackaf/mongo-graphql-starter/blob/74e1ea86703692f465a1d32abd5781b92581be7e/src/queryUtilities.js#L114), [#131](https://github.com/arackaf/mongo-graphql-starter/blob/74e1ea86703692f465a1d32abd5781b92581be7e/src/queryUtilities.js#L131), [#133](https://github.com/arackaf/mongo-graphql-starter/blob/74e1ea86703692f465a1d32abd5781b92581be7e/src/queryUtilities.js#L133),  [#135](https://github.com/arackaf/mongo-graphql-starter/blob/74e1ea86703692f465a1d32abd5781b92581be7e/src/queryUtilities.js#L135).

I was just looking at the code, but it should be easy to reproduce (eg. using a string_startsWith: "+" should cause a SyntaxError since the code would try to `new RegExp("^+", "i")` which is invalid).

**Comment by arackaf** [comment]
Thanks a ton - this should be fixed here https://github.com/arackaf/mongo-graphql-starter/commit/17a067ddab1ae0d3592db64c1e8e63625ab681b0

and published to npm.  If you see anything else wrong, please don't hesitate to reach out.
