### ISSUE TITLE
JSON Type

### ISSUE THREAD

**Issue by erikras** [arackaf/mongo-graphql-starter#21]
How hard would it be to add something like [`graphql-type-json`](https://github.com/taion/graphql-type-json) to this lib?

**Comment by arackaf** [comment]
Probably easy! Lemme take a look in a few days.

**Comment by erikras** [comment]
In case it isn't obvious, I've got a Mongo field where I want to plop a big old JSON object and not have to worry about specifying its precise shape in the GraphQL schema. That's the sort of thing Mongo excels at.

**Comment by arackaf** [comment]
Yep yep!  Should be possible.

**Comment by erikras** [comment]
I looked into implementing this myself and pretty quickly got overwhelmed.

Not to Bill-Lumbergh you too hard, but it would be really awesome if this could get done early this week. 😄 🙏

**Comment by arackaf** [comment]
Yeah the code could be better 😂 

It’s actually an easy implementation (once you know where everything is). I’m flying today - was gonna see about implementing this tomorrow

**Comment by erikras** [comment]
Yeah, I just saw your tweet about airports and felt bad for pressuring you. 😳

**Comment by arackaf** [comment]
@erikras  This should be done, and deployed to npm.  It's not documented (yet) but to see how to use it, check out the PR, in particular files 

test/testProject1/projectSetup.js to see how to add a json property, 

and 

test/testProject1/jsonType.test.js to see how to use it.

https://github.com/arackaf/mongo-graphql-starter/pull/22/files

But the gist is, you can now send arbitrary js content over for a json field, and it'll be saved as is. You can't filter based on the json structure (obviously, it's an arbitrary format, which is the whole point) but you can pull the field down, and update the existing value.

**Comment by erikras** [comment]
This looks good.

I wanna filter on the truthiness of the field, though. i.e. "Does it have a value?" Is that possible?

**Comment by arackaf** [comment]
Hm - yeah that should be possible

**Comment by arackaf** [comment]
@erikras lemme know if you need anything else :)
