### ISSUE TITLE
`TypeError: _c69‍.r is not a function` when trying to run the bootstrapped schema...

### ISSUE THREAD

**Issue by busticated** [arackaf/mongo-graphql-starter#24]
hey there :wave:

thanks for putting this together 👍 

i'm working thru the example and hitting some weird error(s). i suspect it's something having to do with that ol' bear trap `import` in node 🤦‍♂️ 

here's the error i see when running w/ esm via `node ./src/server.js`

```
/graphhhqllll/node_modules/mongo-graphql-starter/node_modules/mongodb/lib/mongo_client.js:1
TypeError: _c69‍.r is not a function
    at Object.<anonymous> (/graphhhqllll/node_modules/mongo-graphql-starter/node_modules/mongodb/lib/mongo_client.js:1)
    at Object.<anonymous> (/graphhhqllll/node_modules/mongo-graphql-starter/node_modules/mongodb/lib/mongo_client.js:1)
    at Module.<anonymous> (/graphhhqllll/node_modules/esm/esm.js:1)
```

when i run w/o esm, i get:

```
/graphhhqllll/src/graphQL/resolver.js:1
(function (exports, require, module, __filename, __dirname) { import GraphQLJSON from 'graphql-type-json';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/graphhhqllll/src/server.js:5:19)
```

esm settings from package.json:

```
  "esm": {
    "cjs": true,
    "mode": "auto",
    "debug": true
  }
```

dependencies from package.json:

```
  "dependencies": {
    "esm": "^3.0.55",
    "express": "^4.16.3",
    "express-graphql": "^0.6.12",
    "graphql": "^0.13.2",
    "graphql-tools": "^3.0.4",
    "mongodb": "^3.1.0"
  }
```

any suggestions you could throw my way would be much appreciated 🙏

**Comment by arackaf** [comment]
Howdy! The version of mongodb you’re on is a full major ahead of what this library was developed against.  I need to get it upgraded, for sure, but pinning to 2.2.31 should fix this

**Comment by busticated** [comment]
🤔 hm. still hitting a similar error:

```
/graphhhqllll/node_modules/mongo-graphql-starter/src/module.js:1
TypeError: _317‍.r is not a function
    at Object.<anonymous> (/graphhhqllll/node_modules/mongo-graphql-starter/src/module.js:1)
    at Object.<anonymous> (/graphhhqllll/node_modules/mongo-graphql-starter/src/module.js:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphhhqllll@1.0.0 start: `node -r esm ./src/server.js`
npm ERR! Exit status 1
```

my installed dependencies (`npm list --depth=0`):

```
graphhhqllll@1.0.0 /graphhhqllll
├── eslint@5.0.1
├── esm@3.0.55
├── express@4.16.3
├── express-graphql@0.6.12
├── graphql@0.13.2
├── graphql-tools@2.23.1
├── mongo-graphql-starter@0.6.17
└── mongodb@2.2.31
```

i downgraded both `mongodb` and `graphql-tools`. 

i think this is all stemming from https://twitter.com/b_sted/status/1012845514461548544 - seems like dependencies aren't being pulled in / specified properly but 🤷‍♂️ 

thanks for taking a look 👍

**Comment by arackaf** [comment]
`0.6.18` is out, which should fix the dependency issue.  I'm gonna test the whole thing from a blank sandbox now, though

**Comment by arackaf** [comment]
This test project is on latest mongo-graphql-starter - everything generates fine, even after a fresh npm install

https://github.com/arackaf/test-mongo-graphql-starter

**Comment by arackaf** [comment]
For good measure I also updated mongo-graphql-starter to use the latest esm package, rather than @std/esm, and I also updated the test project, and also my live booklist project to also use esm.  I updated both of *those* use latest mongo-graphql-starter, and both re-generated my graphql endpoint just fine.

If you're able to track this down to something in my code, please let me know!

**Comment by busticated** [comment]
nice - i'm up and running using `v0.6.19` - thanks a bunch 👍
