### ISSUE TITLE
Implement aggregate $lookup

### ISSUE THREAD

**Issue by ekajogja** [arackaf/mongo-graphql-starter#26]
How to implement aggregate $lookup when querying Author type so that we can get list of Books by authorId without having to add array of Books oid into Author document?

Should we put it inside queryPreAggregate hook? Or could you give an example?

**Comment by arackaf** [comment]
Howdy!  Right now, if a book has a list of authorIds, then all that happens is that each book will have an authors array created, with a corresponding resolver.  There's nothing in principal preventing me from also doing the reverse, and creating a books array in the author, with a resolver that just does the reverse lookup: search all books that have the current author id in the authorIds list.  But it's not done yet.

For now, your best bet would just be to write your own resolver manually.  There are hooks in this library that allow you to integrate your own content; the idea was never to auto-generate every bit of code you'll need, just to get you a good starting point, with most of the boilerplate done.

I'll close the issue, but if you have any other questions, please feel free.
