### ISSUE TITLE
On Update, inserting existing ObjectId 

### ISSUE THREAD

**Issue by ekajogja** [arackaf/mongo-graphql-starter#28]
Problem: During creation, input Id (of existing document) is correctly stored as ObjectId. However, during update, input Id is stored as string.

1. On playground, I use `Updates: { fieldId: "${document._id}" }` since I need to insert existing doc instead of creating a new one.
![screen shot 2018-09-10 at 06 31 43](https://user-images.githubusercontent.com/3442811/45270097-44299b80-b4c3-11e8-90a9-f3bb77291eae.png)

2. Query result after update is good.
![screen shot 2018-09-10 at 06 23 22](https://user-images.githubusercontent.com/3442811/45270069-bc439180-b4c2-11e8-8e53-4650f6174a2f.png)

3. But the oid was stored as string in 1st doc, compared to 2nd doc which was stored during creation.
![screen shot 2018-09-10 at 06 02 26](https://user-images.githubusercontent.com/3442811/45269904-0d9e5180-b4c0-11e8-8529-a0b2c8b6889f.png)

Any advise on how to make Update input also stores as ObjectId?
Thank you.

**Comment by arackaf** [comment]
How is indukOrganisasiId defined in the schema you made for mongo-graphql-starter?  Ie, the code here:

https://github.com/arackaf/mongo-graphql-starter#how-do-you-use-it

Did you use `MongoIdType`?  If so, then the value you send should be cast as ObjectId before saved. If it's defined like that, but the wrapping is not happening, then this is definitely a bug. Let me know

**Comment by ekajogja** [comment]
Yes, I used `MongoIdType`
![screenshot_2018-09-12-16-58-54 2](https://user-images.githubusercontent.com/3442811/45418215-1a809800-b6ae-11e8-8f87-2b1b5f2a27fd.png)
![screenshot_2018-09-12-17-00-08 2](https://user-images.githubusercontent.com/3442811/45418247-2cfad180-b6ae-11e8-89c4-3a5b233f8ba4.png)

**Comment by arackaf** [comment]
Hm ok thanks - I’ll have a look

**Comment by arackaf** [comment]
Hey! Version 0.6.24 is out, which should fix this.  Thanks, and let me know if you see further issues!
