### ISSUE TITLE
Error: Field "BoolType" can only be defined once

### ISSUE THREAD

**Issue by ldellano** [arackaf/mongo-graphql-starter#32]
When I create a Model with a BoolType, in Model/schema.js the BoolType is duplicated and I have to manually delete. Example:

```
const Model = {
...
  valid: BoolType,
...
}
```

```input ModelFilters {
...
  valid: Boolean
  valid: Boolean
  valid_ne: Boolean
  valid_in: [Boolean]
...
}
```

**Comment by arackaf** [comment]
Thanks for reporting this - just to be completely certain, you're on the latest version, right? ie 0.7.3

**Comment by arackaf** [comment]
Ah no - I see it now.  Looks like it's duplicated in the filters object, and also the allTypes query's arguments.

Interestingly my GraphQL engine doesn't complain about it - I may need to upgrade. Regardless though I'll see about getting this fixed and published soon.

**Comment by ldellano** [comment]
Yes. It is now fixed. Thanks a lot!
