### ISSUE TITLE
Question about "Now tell mongo-graphql-starter to create your schema and resolvers"

### ISSUE THREAD

**Issue by MorPelRub97** [arackaf/mongo-graphql-starter#37]
Hello, I am considering using your library in my project, but I have a question. In the Readme.md, where you say: "Now tell mongo-graphql-starter to create your schema and resolvers, like this:"

import {createGraphqlSchema} from "mongo-graphql-starter";
import * as projectSetup from "./projectSetupA";

import path from "path";

createGraphqlSchema (projectSetup, path.resolve ("./test / testProject1"));

I have already created the project setup, but I do not know how to execute your code, can you help me?

**Comment by arackaf** [comment]
You'd run that code with Node.

```javascript
import {createGraphqlSchema} from "mongo-graphql-starter";
import * as projectSetup from "./projectSetupA";

import path from "path";

createGraphqlSchema (projectSetup, path.resolve ("./test / testProject1"));
```

if that file is in createGqlSchema.js, you'd run `node createGqlSchema`

**Comment by MorPelRub97** [comment]
Hello, first of all thank you for responding so quickly. I tried what you told me, but I get this error:

(function (exports, require, module, __filename, __dirname) { import path from "path";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

 I understand why it comes out but not solve it, can you help me?

**Comment by arackaf** [comment]
Ah - sorry.  Yeah, unless you're using the esm package, you can't use regular JavaScript import and export in node.  You'll need to change the above to use require.

Something like this should work 

```javascript
const {createGraphqlSchema} = require("mongo-graphql-starter");
const projectSetup = require("./projectSetupA");

const path = require("path");

createGraphqlSchema (projectSetup, path.resolve ("./test / testProject1"));
```

**Comment by arackaf** [comment]
For real though, you really should use the esm package.  The code this utility emits is standard esm, so Node won't parse it without you either using esm, or running it through babel.

I'd recommend you hit pause, and take 20 minutes to familiarize yourself with it

https://www.npmjs.com/package/esm

**Comment by MorPelRub97** [comment]
Hello, thank you very much for your recommendations. I have been informating myself of the esm package and I will definitely use it in my project. I have also updated node to its latest stable version.

Despite this, when I try to execute the first code that you passed to me, I receive this error:

(function (exports, require, module, __filename, __dirname) {import path from "path";
                                                                     ^^^^

SyntaxError: Unexpected identifier

I have also tried to run it through Babel, but I also get an error:

Error: Can not find module 'mongo-graphql-starter'

I want to execute it in the first way, but I'm stuck, can you help me?

Thank you very much for taking the time to answer me

**Comment by arackaf** [comment]
Start small.  Make sure you're using esm correctly. Read the docs and make sure you understand them.  Get a sample hello world working, that uses import and export.  Once that works you should be able to import anything, ie code from this library.

**Comment by arackaf** [comment]
Closing - feel free to update the thread if you need to though
