### ISSUE TITLE
Add fields meta(count) type graphcool 

### ISSUE THREAD

**Issue by kenyk7** [arackaf/mongo-graphql-starter#4]

**Comment by arackaf** [comment]
Sorry?  I need a bit more info here - not sure what you mean.

**Comment by kenyk7** [comment]
In Graph.Cool existing fields query goal for example:
```gql
_allPostsMeta{
    count
  }
```

to get the number of results in this table

**Comment by johhansantana** [comment]
This is useful for pagination.

**Comment by arackaf** [comment]
I'm actually just now working on changing some of the api around to support sending down more info on queries, like total results (in the whole query), total pages, etc.

That said, the specific feature requested here relates to related data across different tables (collections) which isn't yet implemented. 

Someday soon tho! :)

**Comment by arackaf** [comment]
This is now supported! Check the docs for more info :D
