### ISSUE TITLE
Add relationships to data in other collections 

### ISSUE THREAD

**Issue by kenyk7** [arackaf/mongo-graphql-starter#5]
Is it possible that in the blog example, Blog and Comment are both tables with related fields?

**Comment by arackaf** [comment]
Not yet, but soon.  I definitely want to support relationships between tables, which load related data as needed.  

Closing this, only because it's already high on my todo list.

**Comment by arackaf** [comment]
Just started working on this now

**Comment by arackaf** [comment]
This has been supported for a few versions now.
