### ISSUE TITLE
Check for query before Meta.count db call

### ISSUE THREAD

**Issue by natac13** [arackaf/mongo-graphql-starter#56]
I noticed that you have the ability set up to use the all<Field> query to either get a list of documents, or the count, or both. However I was wondering your thoughts on checking to see if `$project` exists prior to make the `$group` aggregate call. 

Below is generated resovler code from your project.
```js
async allMembers(root, args, context, ast) {
      let db = await (typeof root.db === "function" ? root.db() : root.db);
      await runHook("queryPreprocess", { db, root, args, context, ast });
      context.__mongodb = db;
      let queryPacket = decontructGraphqlQuery(args, ast, MemberMetadata, "Members");
      let { aggregationPipeline } = queryPacket;
      await runHook("queryMiddleware", queryPacket, { db, root, args, context, ast });
      let result = {};

      if (queryPacket.$project) {
        result.Members = await loadMembers(db, aggregationPipeline, root, args, context, ast);
      }

      if (queryPacket.metadataRequested.size) {
        result.Meta = {};

        if (queryPacket.metadataRequested.get("count")) {
          let $match = aggregationPipeline.find(item => item.$match);
          // use if to check for queryPacket.$project of result.Members
          // then use the length of result.Members instead of the following call.
          let countResults = await dbHelpers.runQuery(db, "members", [
            $match,
            { $group: { _id: null, count: { $sum: 1 } } }
          ]);
          result.Meta.count = countResults.length ? countResults[0].count : 0;
        }
      }

      return result;
    }
```

Maybe before getting `countResult` there could be a check if the user asked for the Members with `if (queryPacket.$project)` then use the length of `result.Members` instead of making 2 calls to the DB? This would still leave the ability to get both the list and the count or either or while only making one call.

**Comment by natac13** [comment]
I think I just figured out why you were not doing this.

Is this because you want to be able to get the full count of the documents, even when there is skip, limit or page args?

**Comment by natac13** [comment]
I Was wrong, Result 2 is the actual outcome of the library. So the issue stands. There could be a check to see if the user asked for the documents along with the `Meta.count` data; if so just get a length of the array returned by the aggregation call. If not then proceed as you have it now, with the `$group` call.

**Comment by arackaf** [comment]
Result 1 should be the outcome of the library. The meta count is exactly for getting the total count of all records, not just the ones in the current result set (which may be paginated).

If you see result 1 being returned it's definitely a bug, which I'd be eager to hear more details on. But this does seem to work correctly - just checked.

![image](https://user-images.githubusercontent.com/11261266/71748835-67efbe00-2e39-11ea-9a0f-1638533912e0.png)

**Comment by natac13** [comment]
What brought this to my attention was this [line](https://github.com/arackaf/mongo-graphql-starter/blob/master/src/codeGen/resolverTemplateMethods/allItems.txt#L19). I was just trying to limit the calls to the db.

> The meta count is exactly for getting the total count of all records, not just the ones in the current result set (which may be paginated).

Thank you for clearing this up. :smile: :+1:

**Comment by arackaf** [comment]
Gotcha 👍
