### ISSUE TITLE
Pluralize table name

### ISSUE THREAD

**Issue by natac13** [arackaf/mongo-graphql-starter#57]
When I generate a schema and resolver output using your project, I had the following table names:
- member
- course
- class

Therefore when it came to the generated queries I got 
- getMember
- allMembers
- getCourse
- allCourses
- getClass
- allClasss <---- small fix

When I find where the code is that generates these query names I will make a PR

**Comment by arackaf** [comment]
Let me give this some thought ...

**Comment by duncanhealy** [comment]
mongoose pluralize is done via 
```javascript
exports.pluralization = [
  [/(m)an$/gi, '$1en'],
  [/(pe)rson$/gi, '$1ople'],
  [/(child)$/gi, '$1ren'],
  [/^(ox)$/gi, '$1en'],
  [/(ax|test)is$/gi, '$1es'],
  [/(octop|vir)us$/gi, '$1i'],
  [/(alias|status)$/gi, '$1es'],
  [/(bu)s$/gi, '$1ses'],
  [/(buffal|tomat|potat)o$/gi, '$1oes'],
  [/([ti])um$/gi, '$1a'],
  [/sis$/gi, 'ses'],
  [/(?:([^f])fe|([lr])f)$/gi, '$1$2ves'],
  [/(hive)$/gi, '$1s'],
  [/([^aeiouy]|qu)y$/gi, '$1ies'],
  [/(x|ch|ss|sh)$/gi, '$1es'],
  [/(matr|vert|ind)ix|ex$/gi, '$1ices'],
  [/([m|l])ouse$/gi, '$1ice'],
  [/(kn|w|l)ife$/gi, '$1ives'],
  [/(quiz)$/gi, '$1zes'],
  [/s$/gi, 's'],
  [/([^a-z])$/, '$1'],
  [/$/gi, 's']
];
```

Plurals are bad imo as it confuses the names - this can be fixed in mongoose by passing a third parameter there to the .model, this projects .overides has a way to not change the default resolvers maybe we can extend that to names?!
