### ISSUE TITLE
feature/generate Test Queries

### ISSUE THREAD

**Issue by duncanhealy** [arackaf/mongo-graphql-starter#63]
As part of the generation process I've added a test generation step 
- [x] test all the get{name} Queries
- [x] test all the all{name}s Queries

I'll add a pull request (with .prettierrc update to match rules in project)

**Comment by arackaf** [comment]
Cool man - I’ll get to this as soon as possible - thanks a ton!

**Comment by duncanhealy** [comment]
closed by #67
