### ISSUE TITLE
Relationships not working in object

### ISSUE THREAD

**Issue by vardhmancrayond** [arackaf/mongo-graphql-starter#75]
Hi,

Below is a sample model, relationship is not working in child when a parent is referenced.

```
export const child = {
  fields: {
    name: StringType,
    parent_id: MongoIdType,
  },
  relationships: {
    parent: {
      get type() {
        return parent;
      },
      fkField: "parent_id",
    },
  },
};

export const parent = {
  table:"parent"
  fields: {
   _id:  MongoIdType,
    name: StringType,
    child: arrayof(child),
  },
};

query{
  allparents{
   name
   child {
   name
   parent {    /// This is always null, relationship is not working here.
      name
    }
   }
  }
}
```

**Comment by arackaf** [comment]
Honestly not sure how that query even runs. The `parent` type does not have any relationships defined on it, let alone one called `parent`.

I'd recommend you read closely the docs on how to define relationships on types.

https://github.com/arackaf/mongo-graphql-starter#defining-relationships-between-types
