### ISSUE TITLE
X has many X's and belongs to one X: XMetadata has already been declared

### ISSUE THREAD

**Issue by peebles** [arackaf/mongo-graphql-starter#80]
I have a schema where Organizations belong to an Organization (parent) and have many child Organizations:

```js
export const Organization = {
  table: "Organization",
  fields: {
    name: StringType,
    description: StringType,
    organizationId: MongoIdType,
  },
  relationships: {
    organization: {
      get type() { return Organization },
      fkField: 'organizationId',
      keyField: '_id',
      oneToOne: true,
    },
    organizations: {
      get type() { return Organization },
      fkField: '_id',
      keyField: 'organizationId',
      oneToMany: true,
    },
}
```

The Organization.resolvers.js file ends up with:

```js
...
import OrganizationMetadata from "./Organization";
import OrganizationMetadata from "../Organization/Organization";
...
```

which generates:
  SyntaxError: Identifier 'OrganizationMetadata' has already been declared

If I delete one of those two lines, everything I've tried works so far ... at least queries.  I have not yet tried mutations with related data.

**Comment by arackaf** [comment]
Oh yikes - thanks for the bug - I’ll fix in the next few days

**Comment by arackaf** [comment]
Fixed in https://github.com/arackaf/mongo-graphql-starter/releases/tag/0.11.7
