### ISSUE TITLE
Support Native ESM

### ISSUE THREAD

**Issue by PaulSearcy** [arackaf/mongo-graphql-starter#85]
* Well aware of note in readme

Due to how ESM loader is used in this library , redefines require, I can't treat the library as CJS and just import the default and go from there.

Tried to just import directly from `src/module.js`, but then it throws the error about loading ES modules. The old  **"type":"module" in package.json** which was expected but had to try. 

This is a nice to have. Just wanted to ask since I'll have to wrap my project in the ESM loader again. Again, nbd, thanks for the lbirary!

**Comment by arackaf** [comment]
@PaulSearcy you're best bet will be to use the esm userland loader, and use IT to grab this util. So something like

const express = require("express");

const esmRequire = // setup the esm package - check docs
const mongoGraphQLStarter = esmRequire("mongo-graphql-starter");

I'll close this ticket, but feel free to reply if you have other questions!

**Comment by PaulSearcy** [comment]
@arackaf thanks for the update!

Unfortunately, the file isn't CJS, it's pure ESM and as such `require` isn't allowed. 

It would be worse for my case to go back to CJS like in your example code above then to just wrap everything in the esm loader. 

In addition I tried to convert your code above to ESM, but remembered that module isn't defined in ESM anymore  when I got the reference error message. 

For example 
```
import esm from 'esm';
const esmLoader = esm(module);
```

Won't work and spits out. 
`ReferenceError: module is not defined in ES module scope`

**Comment by arackaf** [comment]
@PaulSearcy Ohhhh - I understand. So sorry, I know next to nothing about Node's native esm. Is there really no way to get the cjs `require` function in a Node esm module? I saw a bunch of things proposed over the last few years, ie 

import require from "require"

Did none of them land?

**Comment by PaulSearcy** [comment]
@arackaf I think I know what your alluding too, but I just remember it as adding another field in package.json to determine what code to serve up based on whether the caller is asking for CJS or ESM. 

`Import require from 'require'` nope.

The main difference between them is that CJS was written for loading libraries from filesystem for Node. While ESM is a standard for loading dependencies in JS with the browser in mind. 

The esm loader additionally supports importing files (not dependencies/libraries listed in package.json)  without requiring the file extension on imports which you can't do in native ESM. 
ex.
```
import  { test } from './testfile';  // Works with esm loader fails on native ESM
import { test2 } from './testfile.js'; // Works in both cases
import { graphql } from 'graphql'; // Works in both cases since it's  dependency listed in package.json
```

I've clone the repo now and am going to see if I can just tweak a few things to remove the need for the loader! If so I'll probably propose a PR.

**Comment by arackaf** [comment]
@PaulSearcy getting this to work with native esm will be a TON of work. Lots and lots and lots of imports will need file extensions added, and I think I'm grabbing some stuff out of node_modules - which may cause this original issue. 

I'll happily accept a PR that makes this work with native esm, I just fear this may be harder than you realize :-|

**Comment by PaulSearcy** [comment]
@arackaf  I know regex https://xkcd.com/208/ 😄
